# Generated by Django 5.0 on 2023-12-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating_count',
        ),
    ]
